name: Build image
on:
  workflow_dispatch:
    inputs:
      target:
        description: Target image to build (coin name)
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make ${{ inputs.target }}_image