name: Publish all images
on:
  push:
    branches:
      - master
jobs:
  publish-bitcoin:
    uses: ./.github/workflows/publish.yml
    with:
      target: bitcoin
    secrets: inherit
  publish-dogecoin:
    uses: ./.github/workflows/publish.yml
    with:
      target: dogecoin
    secrets: inherit
  publish-litecoin:
    uses: ./.github/workflows/publish.yml
    with:
      target: litecoin
    secrets: inherit
  publish-monero:
    uses: ./.github/workflows/publish.yml
    with:
      target: monero
    secrets: inherit
  publish-raven:
    uses: ./.github/workflows/publish.yml
    with:
      target: raven
    secrets: inherit
  publish-wownero:
    uses: ./.github/workflows/publish.yml
    with:
      target: wownero
    secrets: inherit
