name: Publish all images
on:
  push:
    branches:
      - master
jobs:
#  publish-bitcoin:
#    uses: ./.github/workflows/publish.yml
#    with:
#      target: bitcoin
#  publish-dogecoin:
#    uses: ./.github/workflows/publish.yml
#    with:
#      target: dogecoin
#  publish-litecoin:
#    uses: ./.github/workflows/publish.yml
#    with:
#      target: litecoin
#  publish-monero:
#    uses: ./.github/workflows/publish.yml
#    with:
#      target: monero
#  publish-raven:
#    uses: ./.github/workflows/publish.yml
#    with:
#      target: raven
  publish-wownero:
    uses: ./.github/workflows/publish.yml
    with:
      target: wownero